### ISSUE TITLE
Not able list pgvector-cpp in windows

### ISSUE THREAD

**Issue by temporarypassword** [pgvector/pgvector-cpp#4]
Hello,

I am new to vector but old to postgres.

Is there any tutorial steps to install pgvector-cpp on windows and some sample cpp file to do vector search

Any lead is helpful

**Comment by ankane** [comment]
Hi @temporarypassword, I'm not aware of any tutorials. The [test file](https://github.com/pgvector/pgvector-cpp/blob/master/test/pqxx_test.cpp) might be helpful. In general, I'd recommend getting libpqxx working without pgvector, then following the instructions in the readme (if you run into the error from #3, use `master` instead of `v0.1.1` when cloning). You could also copy [the headers](https://github.com/pgvector/pgvector-cpp/tree/master/include) directly into your project if you don't want to install it globally.
